#!/bin/sh

## Select digraph, or enter dk, jp, es, fr, or tr to have the text ran through eithre a parser or through translate
dansk() {
	echo "$@" | sed 's|ae|æ|g;s|/o|ø|g;s|a^|å|g;s|AE|Æ|g;s|/O|Ø|g;s|A^|Å|g'
}

espana() {
#á, é, í, ó, ú, ý, ï, ü, Ü, ¿, and ¡. Á, É, Í, Ó, Ú, and Ý
	echo "$@" | s ed 's/~n/ñ/g;s/~N/Ñ/g'
}

jp() {}

french() {}

transl() {}

# Select a digraph from list to input
result="`dmenu`" <<EOF
$(xcmenu --get 0)
!! ¡
cent ¢
pound £
currency ¤
yen ¥
vert ¦
section §
umlaut ¨
copyright ©
trademark ™
<< «
not ¬
registered ®
overline ¯
degree °
+- ±
squared ²
cubed ³
\` ´
micro µ
dot ·
1 ¹
>> »
?? ¿
x ×
/ ÷
dk
sp
jp
fr
tr
EOF
case "$result" in
	dk\ *) result="`dansk  "${result#dk }"`" ;;
	es\ *) result="`espana "${result#es }"`" ;;
	jp\ *) result="`jp     "${result#jp }"`" ;;  
	fr\ *) result="`french "${result#fr }"`" ;; 
	tr\ *) result="`transl "${result#tr }"`" ;;
	*) result="${result##* }" ;;
esac
xdotool type --clearmodifiers --delay 50 -window "`lsw | tail -n 1`" "$result"
