#!/bin/bash

crawl() {
        for i in "$1"/*; do
                cd "$i" || continue
                if git rev-parse --is-inside-work-tree &>/dev/null; then
                       git fetch &>/dev/null &
                       [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) ]] >/dev/null || printf '%s\n' "${i/$HOME/}"
                else
                        crawl "$i" &
                        wait
                fi
        done
}

# Clean up pulls 
cleanit() {
	crawl "$HOME/local/src" | sed 's|/local/src/||' > "$XDG_DATA_HOME"/pulls
	/usr/local/share/hwwm/gitbar
}

terminalize() {
	tmp="$(mktemp)"
	while read -r in; do
		cd "$HOME/local/src/$in"
		git diff HEAD origin/HEAD --color > "$tmp"
		st -e less -R "$tmp"
	done
	rm "$tmp"
}

dmenu -p "Repo to view: " < "$XDG_DATA_HOME"/pulls | terminalize

cleanit
