#!/usr/bin/env bash

crawl() {
        for i in "$1"/*; do
                cd "$i" || continue
                if git rev-parse --is-inside-work-tree &>/dev/null; then
                       git fetch &>/dev/null &
                       [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) ]] >/dev/null || printf '%s\n' "${i/$HOME/}"
                else
                        crawl "$i" &
                        wait
                fi
        done
}

terminalize() {
	while read -r in; do
		test "$in" = "quit" && return 1
		cd "$HOME/local/src/$in" || continue
		tmp="$(mktemp)"
		git diff HEAD origin/HEAD --color > "$tmp"
		$TERMINAL -e less -R "$tmp"
		pkill $$
		rm "$tmp"
		"$XDG_CONFIG_HOME/git/template/hooks/post-merge"
	done
}

# Exit early if we have no entries in pulls file
test $(wc -l < "$XDG_DATA_HOME/pulls") -gt 0 || exit 0

dmenu -p "Repo to view (type quit to exit): " < "$XDG_DATA_HOME"/pulls | terminalize && exec $0
