#!/bin/bash
# Branches should be handled with much more care, do not use for branches
crawl() {
		for i in $1/*; do
				if test -d $i 2>/dev/null; then
						cd "$i"
				else
						continue
				fi
				
				if git rev-parse --is-inside-work-tree &>/dev/null; then
					   git fetch &>/dev/null & 
					   [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) ]] >/dev/null || printf '%s\n' "${i/$HOME/}"
				else
					   crawl "$i"
				fi
		done
}

handle_results() {
		while read -r url; do
				cd "$HOME${url%%\ *}"
				git pull && continue 
				stat=$(git status)
				st -e varless "$stat"
		done
}
if [[ $1 == "wc" ]]; then
	crawl "$HOME/local" | wc -l
else
	crawl "$HOME/local" | dmenu -p "Pull repos: " | handle_results 
	"$XDG_DATA_HOME"/x11/gitbar &
fi
