#!/bin/bash
# Branches should be handled with much more care, do not use for branches

check() {
	cd "$1" || return 0
	if git status 2>/dev/null | grep -q ahead; then
		printf '%s\n' "${1/$HOME/}"
		return 1
	fi
	return 0
}

crawl() {
		for i in "$1"/*; do
				cd "$i" 2>/dev/null || continue
				check "$i" && crawl "$i" &
		done
}

# =^.^=
parse_dirs() {
	cat <(crawl ~/code) <(check "$XDG_CONFIG_HOME") <(check "$XDG_DATA_HOME/blog") > "$XDG_DATA_HOME/pushes"
	/usr/local/share/hwwm/gitbar
}

terminalize() {
	while read -r in; do
		test "$in" = "quit" && return 1
		cd "$HOME${in%%\ *}" || continue
		st -g 60x1+20+20 -c float -e git push
	done
}

# Initialize
parse_dirs

# Exit early if we have no entries in pulls file
test $(wc -l < "$XDG_DATA_HOME/pushes") -gt 0 || exit 0

# choose folder
dmenu -p "Repo to push (type quit to exit): " < "$XDG_DATA_HOME/pushes" | terminalize && exec $0 || parse_dirs
