#!/bin/bash
# Branches should be handled with much more care, do not use for branches

check() {
	cd "$1" || return 0
	if git  rev-parse --is-inside-work-tree &>/dev/null; then
		case "$(git status | sed -n 2p)" in
			*ahead*) printf '%s\n' "${i/$HOME/}" 
					return 1;;
		esac	
	fi
	return 0
}

crawl() {
		for i in $1/*; do
				if test -d $i 2>/dev/null; then
						cd "$i"
				else
						continue
				fi
				check "$i" && crawl "$i" &
		done
}

handle_results() {
		while read -r url; do
				cd "$HOME${url%%\ *}"
				st -g 60x1+20+20 -t float -e git push
						:
		done
}

# =^.^=
if [[ $1 == "wc" ]]; then
	cat <(crawl ~/code) <(check "$XDG_CONFIG_HOME") | wc -l
else
	cat <(crawl ~/code) <(check "$XDG_CONFIG_HOME") | dmenu -p "Push repo: " | handle_results 
	/usr/local/share/hwwm/gitbar push &
fi
