#!/bin/sh
## Requires xdotool

run_term() {
	st -o - -g 60x1+20+20 -c float -e mpw -t max
}

layout="$(setxkbmap -query | awk '/layout/{print $NF}')"
pw="$(run_term | awk '/]: /{print $NF}')"
# Normalize input
setxkbmap -layout us
xdotool type --clearmodifiers --delay 50 --window "$(lsw | tail -n 1)" "$pw"
setxkbmap -layout "$layout"