#!/bin/bash

trap 'clean' EXIT SIGINT SIGHUP

clean() {
	echo "" > "$XDG_RUNTIME_DIR/statusbar/media"
}

# Kill off any running processes
if pgrep mpg123; then
	pkill mpg123
fi
mpg123 --no-control -b 1024 -@ "$@" &>/dev/stdout | while read -r line; do
	echo "$line" | grep StreamTitle | sed "s/ICY-META: StreamTitle='/ /;s/';StreamUrl=.*//;s/\[.*\]//;s/-.*-/-/;s/([0-9].*:[0-9][0-9])//;s/';$//" | tail -c 80 > "$XDG_RUNTIME_DIR/statusbar/media"
done
