#!/bin/sh

trap 'clean' EXIT HUP INT

clean() {
	echo "" > "$XDG_RUNTIME_DIR/statusbar/media"
}

if pgrep ogg123; then
	pkill ogg123
	exit 0
fi

ogg123 -p 5 -b 512 "http://192.168.0.203:28129" 2>&1 /dev/stdout | while read -r line; do
	mpc current > $XDG_RUNTIME_DIR/statusbar/media
done

