#!/bin/bash

trap 'clean' EXIT SIGINT SIGHUP

clean() {
	echo "" > "$XDG_RUNTIME_DIR/statusbar/media"
}

if pgrep ogg123; then
	pkill ogg123
	exit 0
fi

ogg123 --no-control -p 5 -b 512 "http://servy:28129" &>/dev/stdout | awk '/Title: /{$1 = ""; print}' | while read -r line; do
	printf '%s\n' "$line" > "$XDG_RUNTIME_DIR/statusbar/media"
done
