#!/bin/bash
# sx - simpler startx

# Make sure we aren't already running in an Xserver.
[[ $DISPLAY ]] && exit 1

tty=$(fgconsole) || exit 1

# Honour XINITRC as per xinit(1) documentation.
xinitrc=${XINITRC:-$HOME/local/cfg/x11/xinitrc}

export DISPLAY=:$tty

exec xinit "${@:-$xinitrc}" -- "$DISPLAY" vt"$tty" -keeptty
