#!/bin/sh

# Source folder
CODE="${1:-$HOME/code}"

# Make sure we're not on a file
if ! test -d "$CODE"; then
	CODE="$(dirname "$CODE")"
fi

# Walk up if we're in a directory
if git rev-parse --is-inside-work-tree 2>/dev/null; then
	CODE=$(git rev-parse --show-toplevel)
fi

handle() {
	IFS=':'
	while read -r line number _; do
		echo "+$number $line"
	done
} 

# Regex is fickle, and only matches specific `TODO:` and `BUG:` strings
grep -nR -e 'TODO:' -e 'BUG:' $CODE \
	| sed 's/\(:.*:\)\(.*\)\([TODO|BUG]\):/\1 - \2\3/' \
	| dmenu -p "Select file to complete: " \
	| handle \
	| plumb -i
