#!/bin/sh

# Source folder
CODE="${1:-$HOME/code}"

# Make sure we're not on a file
if ! test -d "$CODE"; then
	CODE="$(dirname "$CODE")"
fi

# Walk up if we're in a directory
if git rev-parse --is-inside-work-tree 2>/dev/null; then
	CODE=$(git rev-parse --show-toplevel)
fi

handle() {
	IFS=':'
	while read -r line number _; do
		echo "+$number $line"
	done
} 

grep -nR 'TODO:' $CODE | sed 's/\(:.*:\)\(.*\)TODO:/\1 - \2TODO:/' | dmenu -p "Select file to complete: " | handle | plumb -i
