#!/bin/bash
## This could make a lot of watches. 

files=(
	"/home/halfwit/code"
	"/home/halfwit/local/cfg"
	"/home/halfwit/local/share/blog"
)	

# One case where quotations hurt.
inotifywait -qmre close_write ${files[*]} |  while read -r path _ file; do
	case "$file" in
		*zsh_history) continue ;;
	esac
	cd "$path" || continue
	if git diff --shortstat 2>/dev/null | grep -q changed; then
		grep -q "${in/$HOME/}" "$XDG_DATA_DIR/commits" && continue
		printf '%s\n' "${in/$HOME/}" >> "$XDG_DATA_DIR/commits"
	fi

	/usr/local/share/hwwm/gitbar

done
