#!/usr/bin/env bash
## This could make a lot of watches. 

files=(
	"/home/halfwit/code"
	"/home/halfwit/local/cfg"
	"/home/halfwit/local/data/blog"
)	

check() {
	grep "$1" "$XDG_DATA_HOME/commits" || printf '%s\n' "$1" >> "$XDG_DATA_HOME/commits"
}

# One case where quotations hurt.
inotifywait -qmre close_write ${files[*]} | while read -r path _ file; do
	test "$file" = ".zsh_history" && continue 
	cd "$path" || continue
	if git diff --shortstat 2>/dev/null | grep -q changed; then
		check "${path%*/}"
	fi

	/usr/local/share/hwwm/gitbar

done
