#!/usr/bin/env bash

## Script to fetch RSS + atom feeds 
RSS="$XDG_CACHE_HOME"/rss

fetch_data() {
	data=$(curl -sBX GET -L "$1" -A "Mozilla/5.0 (Linux; Android 6.0.1; Nexus  MOB3OD)" | xml2 | sed 's|/feed/entry/title/@type||')
	case "$data" in
		*itunes*podcast*1.0*)	echo "$data" | grep -e '/rss/channel/item/enclosure/@url' -e '/rss/channel/item/title' ;;
		*xmlns:rdf*)		echo "$data" | grep -e 'RDF/item/title'-e 'RDF/item/link' ;;
		*rss*version*2.0*)	echo "$data" | grep -e '/rss/channel/item/title' -e '/rss/channel/item/link' ;;
		*Atom*)				echo "$data" | grep -e '/feed/entry/title' -e '/feed/entry/link.*href' ;;
		*atom*)				echo "$data" | grep -e '/feed/entry/title' -e '/feed/entry/link.*href' ;;
		*) echo "Mismatch on $1" >> ~/rss_issue && exit 0 ;;
	esac
}

build_folders() {

	while {
		read -r first
		read -r second
	} do

		#This sucks, but whatever
		case "$first" in
			*feed*entry*title=*)	title="$(echo "$first"	| sed 's|/feed/entry/title=||' | sed 's|/||g')"
						link="$(echo "$second"	| xurls)" ;;
			*rss*item*title*)	title="$(echo "$first"	| sed 's|/rss/channel/item/title=||' | sed 's|/||g')"
						link="$(echo "$second"	| xurls)" ;;
			*rdf*item*title*)	title="$(echo "$first"	| sed 's|/rdf:RDF/item/title=||' | sed 's|/||g')"
						link="$(echo "$second"	| xurls)" ;;
			*enclosure*)		title="$(echo "$second" | sed 's|/rss/channel/item/title=||' | sed 's|/||g')"
						link="$(echo "$first"	| xurls)" ;;
			*rdf*item*link*)	title="$(echo "$second" | sed 's|/rdf:RDF/item/title=||' | sed 's|/||g')"
						link="$(echo "$first"	| xurls)" ;;
			*rss*item*link*)	title="$(echo "$second" | sed 's|/rss/channel/item/title=||' | sed 's|/||g')"
						link="$(echo "$first"	| xurls)" ;;
			*feed*entry*link*)	title="$(echo "$second" | sed 's|/feed/entry/title=||' | sed 's|/||g')"
						link="$(echo "$first"	| xurls)" ;;
			*)			echo "Mismatch with item $first $second in $i" >> ~/rss_issue && exit 0 ;;
		esac

		if [[ ! -f "$RSS/$1/$title" ]]; then
			echo "$link" > "$RSS/$1/[new] $title"
		fi
	done
}

while :; do

	cd "$RSS"
	for i in *; do
		if [[ $i == ".stfolder" ]] || [[ $i == "count" ]]; then
			continue
		fi
		read -r url < "$i"/url 
		fetch_data "$url" | build_folders "$i"
	done 
	find ~/local/cache/rss -name "\[new\]*" | wc -l > $RSS/count
	sleep 1774
done
