#!/usr/bin/env bash

## Script to fetch RSS + atom feeds 
## See ://gist.github.com/halfwit/d5251e2b0e58c1f5199c49dfbf836e5d for sample xslt files to use
RSS="$XDG_CACHE_HOME"/rss

tmp="$(mktemp)"

fetch_data() {
	curl -sL "$1" -o "$tmp"
	xml tr "$XDG_DATA_HOME"/xslt/"$(xml el "$tmp" | head -n 1)".xslt "$tmp"
}

build_folders() {
	while read -r link title; do
		if [[ ! -f "$RSS/$1/$title" ]]; then
			mkdir -p "$(dirname "$RSS/$1/[new] $title")"
			echo "$link" > "$RSS/$1/[new] $title"
		fi
	done
}

while :; do

	cd "$RSS"
	for i in *; do
		if [[ $i == ".stfolder" ]] || [[ $i == "count" ]]; then
			continue
		fi
		read -r url < "$i"/url 
		fetch_data "$url" | build_folders "$i"
	done 
	find ~/local/cache/rss -name "\[new\]*" | wc -l > $RSS/count
	sleep 1774
done
