#!/bin/bash

# This will change to something cron can run, which will set a file with a list of repositories that can be pulled from.
# A complementary script will be made to list the `git diff` of changes to upstream and facilitate a `git apply` to the patch. 
# Additional branch management will be implemented in future revisions

# Branches should be handled with much more care, do not use for branches
crawl() {
		for i in "$1"/*; do
				cd "$i" || continue
				if git rev-parse --is-inside-work-tree &>/dev/null; then
					   git fetch &>/dev/null & 
					   [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) ]] >/dev/null || printf '%s\n' "${i/$HOME/}"
				else
						crawl "$i" &
						wait
				fi
		done
}

crawl "$HOME/local/src" | sed "s|/local/src/||" > "$XDG_DATA_HOME"/pulls
/usr/local/bin/gitbar
/usr/local/share/hwwm/githbar
