#!/bin/sh --

# Schema is as follows
# someuri.somedomain/some/path, anything that satisfies this
# ~/a/path/to/somewhere
# /a/path/to/somewhere

filter() {
	case $1 in
		# Special case to hit <someurl.com>
		http://*|https://*|git://*) echo "$1" ;;
		\<[a-zA-Z0-9-_]*.[a-zA-Z0-9-_]*/[a-zA-Z0-9-_]*) echo "$1" | sed 's|<|https://|;s|>||'  ;;
		[a-zA-Z0-9-_]*.[a-zA-Z0-9-_]*/[a-zA-Z0-9-_~]*) echo "https://$1"  ;;
		/[a-zA-Z0-9.-_]*/[a-zA-Z0-9.-_]*) echo "$1" ;;
		\~/[a-zA-Z0-9.-_]*) echo "$1" ;;
		[a-zA-Z0-9-_]*.[a-zA-Z][a-zA-Z][a-zA-Z]) echo "https://$1" ;;
		[a-zA-Z0-9-_]*.[a-zA-Z][a-zA-Z]) echo "https://$1" ;;
		[a-zA-Z0-9-_]*.[a-zA-Z]) echo "https://$1" ;;
	esac
}

# Complex little bit of shell redirection which allows piping of the stdin through tr as well as not (removing control chars in weechat, for example)
{ { tee /dev/fd/3 | tr -d "[:cntrl:]" >&9;
	} 3>&1 >&9; 
} 9>&1 | while read -r line; do
	# Chunk out lines into words and run them through filter
	for i in $line; do
		filter "$i"
	done
done | sed 's/^.*\(http.*$\)/\1/;s|file://||;s/…//' | uniq | tac | dmenu -p links | xe -s 'plumber $1'