#!/usr/bin/env bash
# Cheapo url spawner for st

# https://github.com/mvdan/xurls
# https://github.com/Cloudef/bemenu
# Currently strips newlines as well

tmp=$(mktemp)

menu() {
    tac | dmenu -p URLs
}

url_scrub() {
    local item
    tee $tmp | tr -d "[:cntrl:]" | xurls | while read -r item; do
        case "$item" in
            *http://*|*https://*) sed 's/^.*\(http.*$\)/\1/' <<< "$item" ;;
            *file:///*)           sed 's|file://||'          <<< "$item" ;;
            *)                    printf '%s\n' "$item"                  ;;
        esac
    done
	sed 's|file://||' "$tmp" | xurls

}

handle() {
	local selection
	while read -r selection; do
		plumber "$selection" 
	done
	rm "$tmp"
}

url_scrub "$@" | menu | handle
